// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY', // You'll need to get this from Firebase Console
    appId: 'YOUR_WEB_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // You'll need to get this from Firebase Console
    projectId: 'budgease-460b5',
    authDomain: 'budgease-460b5.firebaseapp.com',
    storageBucket: 'budgease-460b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // You'll need to get this from Firebase Console
    appId: 'YOUR_ANDROID_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // You'll need to get this from Firebase Console
    projectId: 'budgease-460b5',
    storageBucket: 'budgease-460b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // You'll need to get this from Firebase Console
    appId: 'YOUR_IOS_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID', // You'll need to get this from Firebase Console
    projectId: 'budgease-460b5',
    storageBucket: 'budgease-460b5.appspot.com',
    androidClientId: 'YOUR_ANDROID_CLIENT_ID', // You'll need to get this from Google Cloud Console
    iosClientId: 'YOUR_IOS_CLIENT_ID', // You'll need to get this from Google Cloud Console
    iosBundleId: 'com.budget.tracker-app',
  );
}
